create table public.courses (
  id bigint generated by default as identity primary key,
  title varchar(150) not null,
  slug varchar(160) not null unique,
  description text,
  language varchar(50) not null default 'Python',
  level varchar(50) not null default 'Beginner',
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint courses_title_length check (char_length(trim(title)) between 1 and 150),
  constraint courses_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table public.chapters (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete restrict,
  title varchar(150) not null,
  description text,
  chapter_order integer not null,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chapters_course_order_unique unique (course_id, chapter_order),
  constraint chapters_order_positive check (chapter_order > 0)
);

create table public.lessons (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.chapters(id) on delete restrict,
  title varchar(150) not null,
  content text,
  lesson_order integer not null,
  estimated_minutes integer,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lessons_chapter_order_unique unique (chapter_id, lesson_order),
  constraint lessons_order_positive check (lesson_order > 0),
  constraint lessons_estimated_minutes_positive
    check (estimated_minutes is null or estimated_minutes > 0)
);

create table public.exercises (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete restrict,
  title varchar(150) not null,
  description text,
  exercise_type public.exercise_type not null,
  difficulty public.difficulty_level not null default 'easy',
  code_snippet text,
  exercise_order integer not null,
  is_required boolean not null default true,
  is_published boolean not null default false,
  source public.exercise_source not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint exercises_lesson_order_unique unique (lesson_id, exercise_order),
  constraint exercises_order_positive check (exercise_order > 0)
);

create table public.exercise_options (
  id bigint generated by default as identity primary key,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  content text not null,
  option_order integer not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint exercise_options_exercise_order_unique unique (exercise_id, option_order),
  constraint exercise_options_order_positive check (option_order > 0),
  constraint exercise_options_content_not_blank check (char_length(trim(content)) > 0)
);

create table public.exercise_solutions (
  exercise_id bigint primary key references public.exercises(id) on delete cascade,
  solution jsonb not null,
  static_explanation text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
