create table public.course_enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete restrict,
  status public.enrollment_status not null default 'active',
  enrolled_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint course_enrollments_user_course_unique unique (user_id, course_id)
);

create table public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete restrict,
  status public.progress_status not null default 'locked',
  started_at timestamptz,
  completed_at timestamptz,
  last_accessed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_progress_user_lesson_unique unique (user_id, lesson_id)
);

create table public.submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete restrict,
  exercise_id bigint not null references public.exercises(id) on delete restrict,
  answer jsonb not null,
  is_correct boolean not null,
  score numeric(5, 2),
  attempt_number integer not null,
  submitted_at timestamptz not null default now(),
  constraint submissions_user_exercise_attempt_unique
    unique (user_id, exercise_id, attempt_number),
  constraint submissions_attempt_positive check (attempt_number > 0),
  constraint submissions_score_range
    check (score is null or (score >= 0 and score <= 100))
);
