create table public.ai_explanations (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.submissions(id) on delete cascade,
  user_question text,
  response text,
  provider varchar(50) not null,
  model varchar(100),
  status public.ai_response_status not null,
  error_code varchar(100),
  created_at timestamptz not null default now()
);
